name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # In case you use git submodules

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Enable Flutter web (optional)
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Upgrade dependencies
        run: flutter pub upgrade

      - name: Build generated files (build_runner)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test