name: Build [Android]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && (github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'noci')) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build debug APK
      run: ./gradlew androidApp:assembleDebug

    - name: Build release APK
      run: ./gradlew androidApp:assembleRelease

    - name: List APKs
      run: ls -R androidApp/build/outputs/apk/

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: spmp-android-debug
        path: androidApp/build/outputs/apk/debug/*.apk

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: spmp-android-release
        path: androidApp/build/outputs/apk/release/*.apk